/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRAMES;

import java.util.HashMap;
import java.util.function.Consumer;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author REGIE
 */
public class KantoKusina_Frame extends javax.swing.JFrame {
   DefaultTableModel model =  new DefaultTableModel();
     HashMap<String, Double> foodPrices = new HashMap<>();

    private String selectedFood = "";
    private double selectedPrice = 0.0;
    private int selectedQuantity = 1;
    
    
    public KantoKusina_Frame() {
        initComponents();
        
        foodPrices.put("Pu1", 50.00);
        foodPrices.put("Pu2", 50.00);
        foodPrices.put("Pu3", 50.00); 
        foodPrices.put("Pu4", 50.00); 
        foodPrices.put("Pu5", 50.00); 
        foodPrices.put("Pu6", 50.00); 
        
        foodPrices.put("P1", 50.00); 
        foodPrices.put("P2", 50.00); 
        foodPrices.put("P3", 50.00); 
        foodPrices.put("P4", 50.00); 
        foodPrices.put("P5", 50.00); 
        foodPrices.put("P6", 50.00); 
        
        foodPrices.put("Ph1", 50.00); 
        foodPrices.put("Ph2", 50.00); 
        foodPrices.put("Ph3", 50.00); 
        foodPrices.put("Ph4", 50.00); 
        foodPrices.put("Ph5", 50.00); 
        foodPrices.put("Ph6", 50.00); 
    }
    
     private void updateTotalAmount() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    double total = 0.0;
    for (int i = 0; i < model.getRowCount(); i++) {
        Object amountValue = model.getValueAt(i, 2);
        if (amountValue instanceof Number) {
            total += ((Number) amountValue).doubleValue();
        } else if (amountValue instanceof String) {
            try {
                total += Double.parseDouble((String) amountValue);
            } catch (NumberFormatException e) {
                // ignore invalid numbers
            }
        }
    }
    jLabel2.setText("₱" + String.format("%.2f", total));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        Ulam = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        puSpinner1 = new javax.swing.JSpinner();
        puSpinner2 = new javax.swing.JSpinner();
        puSpinner3 = new javax.swing.JSpinner();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        puSpinner4 = new javax.swing.JSpinner();
        puSpinner5 = new javax.swing.JSpinner();
        puSpinner6 = new javax.swing.JSpinner();
        Pulutan = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        pSpinner1 = new javax.swing.JSpinner();
        pSpinner2 = new javax.swing.JSpinner();
        pSpinner3 = new javax.swing.JSpinner();
        pSpinner4 = new javax.swing.JSpinner();
        pSpinner5 = new javax.swing.JSpinner();
        pSpinner6 = new javax.swing.JSpinner();
        Panghimagas = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        phSpinner1 = new javax.swing.JSpinner();
        phSpinner2 = new javax.swing.JSpinner();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        phSpinner4 = new javax.swing.JSpinner();
        phSpinner5 = new javax.swing.JSpinner();
        jButton26 = new javax.swing.JButton();
        phSpinner3 = new javax.swing.JSpinner();
        jButton22 = new javax.swing.JButton();
        phSpinner6 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(8, 61, 53));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 125));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/header2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 675));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/6.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -79;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 7, 0, 0);
        jPanel1.add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/7.png"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -79;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 7, 0, 0);
        jPanel1.add(jButton2, gridBagConstraints);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8.png"))); // NOI18N
        jButton3.setText("jButton3");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = -79;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 7, 0, 0);
        jPanel1.add(jButton3, gridBagConstraints);

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 78;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 1, 0, 0);
        jPanel1.add(jButton4, gridBagConstraints);

        jButton5.setText("Delete ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 78;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 1, 0, 0);
        jPanel1.add(jButton5, gridBagConstraints);

        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 78;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 1, 0, 0);
        jPanel1.add(jButton6, gridBagConstraints);

        jButton7.setText("Pay");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 78;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 1, 29, 0);
        jPanel1.add(jButton7, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(8, 61, 53));
        jPanel4.setPreferredSize(new java.awt.Dimension(549, 240));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order", "Quantity", "Amount", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 438;
        gridBagConstraints.ipady = 99;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(35, 67, 0, 64);
        jPanel4.add(jScrollPane2, gridBagConstraints);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Amount:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 67, 52, 0);
        jPanel4.add(jLabel1, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 52, 0);
        jPanel4.add(jLabel2, gridBagConstraints);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new javax.swing.OverlayLayout(jPanel5));

        Ulam.setBackground(new java.awt.Color(255, 255, 255));
        Ulam.setPreferredSize(new java.awt.Dimension(630, 1377));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/29.png"))); // NOI18N
        jButton8.setText("jButton8");
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/30.png"))); // NOI18N
        jButton9.setText("jButton9");
        jButton9.setBorderPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/31.png"))); // NOI18N
        jButton10.setText("jButton10");
        jButton10.setBorderPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/32.png"))); // NOI18N
        jButton11.setText("jButton11");
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/33.png"))); // NOI18N
        jButton12.setText("jButton12");
        jButton12.setBorderPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/34.png"))); // NOI18N
        jButton13.setText("jButton13");
        jButton13.setBorderPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UlamLayout = new javax.swing.GroupLayout(Ulam);
        Ulam.setLayout(UlamLayout);
        UlamLayout.setHorizontalGroup(
            UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UlamLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UlamLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UlamLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(puSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UlamLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 122, Short.MAX_VALUE))
        );
        UlamLayout.setVerticalGroup(
            UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UlamLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puSpinner1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(puSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(puSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(puSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 948, Short.MAX_VALUE))
        );

        jPanel5.add(Ulam);

        Pulutan.setBackground(new java.awt.Color(255, 255, 255));

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/35.png"))); // NOI18N
        jButton14.setText("jButton14");
        jButton14.setBorderPainted(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/36.png"))); // NOI18N
        jButton15.setText("jButton15");
        jButton15.setBorderPainted(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/37.png"))); // NOI18N
        jButton16.setText("jButton16");
        jButton16.setBorderPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/38.png"))); // NOI18N
        jButton17.setText("jButton17");
        jButton17.setBorderPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(255, 255, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/39.png"))); // NOI18N
        jButton18.setText("jButton18");
        jButton18.setBorderPainted(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(255, 255, 255));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/40.png"))); // NOI18N
        jButton19.setText("jButton19");
        jButton19.setBorderPainted(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PulutanLayout = new javax.swing.GroupLayout(Pulutan);
        Pulutan.setLayout(PulutanLayout);
        PulutanLayout.setHorizontalGroup(
            PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PulutanLayout.createSequentialGroup()
                .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PulutanLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PulutanLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(pSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PulutanLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PulutanLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(pSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PulutanLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PulutanLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(pSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PulutanLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(pSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PulutanLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PulutanLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(pSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PulutanLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(pSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        PulutanLayout.setVerticalGroup(
            PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PulutanLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PulutanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1262, Short.MAX_VALUE))
        );

        jPanel5.add(Pulutan);

        Panghimagas.setBackground(new java.awt.Color(255, 255, 255));

        jButton20.setBackground(new java.awt.Color(255, 255, 255));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/41.png"))); // NOI18N
        jButton20.setText("jButton20");
        jButton20.setBorderPainted(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(255, 255, 255));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/42.png"))); // NOI18N
        jButton21.setText("jButton21");
        jButton21.setBorderPainted(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(255, 255, 255));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/44.png"))); // NOI18N
        jButton23.setText("jButton23");
        jButton23.setBorderPainted(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(255, 255, 255));
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/45.png"))); // NOI18N
        jButton24.setText("jButton24");
        jButton24.setBorderPainted(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton26.setBackground(new java.awt.Color(255, 255, 255));
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/43.png"))); // NOI18N
        jButton26.setText("jButton26");
        jButton26.setBorderPainted(false);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(255, 255, 255));
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KantoImages/46.png"))); // NOI18N
        jButton22.setText("jButton22");
        jButton22.setBorderPainted(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanghimagasLayout = new javax.swing.GroupLayout(Panghimagas);
        Panghimagas.setLayout(PanghimagasLayout);
        PanghimagasLayout.setHorizontalGroup(
            PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanghimagasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanghimagasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanghimagasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanghimagasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        PanghimagasLayout.setVerticalGroup(
            PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanghimagasLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanghimagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1263, Short.MAX_VALUE))
        );

        jPanel5.add(Panghimagas);

        jScrollPane1.setViewportView(jPanel5);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ulam.setVisible(true);
        Pulutan.setVisible(false);
        Panghimagas.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Ulam.setVisible(false);
        Pulutan.setVisible(true);
        Panghimagas.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Ulam.setVisible(false);
        Pulutan.setVisible(false);
        Panghimagas.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
         selectedFood = "Ph2";
    selectedPrice = foodPrices.get("Ph2");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         selectedFood = "Pu1";
    selectedPrice = foodPrices.get("Pu1");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        selectedFood = "Pu2";
    selectedPrice = foodPrices.get("Pu2");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         selectedFood = "Pu3";
    selectedPrice = foodPrices.get("Pu3");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
         selectedFood = "Pu4";
    selectedPrice = foodPrices.get("Pu4");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         selectedFood = "Pu5";
    selectedPrice = foodPrices.get("Pu5");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       selectedFood = "Pu6";
    selectedPrice = foodPrices.get("Pu6");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
      selectedFood = "P1";
    selectedPrice = foodPrices.get("P1");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
         selectedFood = "P2";
    selectedPrice = foodPrices.get("P2");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        selectedFood = "P3";
    selectedPrice = foodPrices.get("P3");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        selectedFood = "P4";
    selectedPrice = foodPrices.get("P4");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        selectedFood = "P5";
    selectedPrice = foodPrices.get("P5");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        selectedFood = "P6";
    selectedPrice = foodPrices.get("P6");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        selectedFood = "Ph1";
    selectedPrice = foodPrices.get("Ph1");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
         selectedFood = "Ph3";
    selectedPrice = foodPrices.get("Ph3");
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
         selectedFood = "Ph4";
    selectedPrice = foodPrices.get("Ph4");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
         selectedFood = "Ph5";
    selectedPrice = foodPrices.get("Ph5");
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed

         selectedFood = "Ph6";
    selectedPrice = foodPrices.get("Ph6");
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if (selectedFood.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please select a food item first.");
    return;
}
// Determine selected quantity
    switch (selectedFood) {
    case "Pu1": selectedQuantity = (Integer) puSpinner1.getValue(); break;
    case "Pu2": selectedQuantity = (Integer) puSpinner2.getValue(); break;
    case "Pu3": selectedQuantity = (Integer) puSpinner3.getValue(); break;
    case "Pu4": selectedQuantity = (Integer) puSpinner4.getValue(); break;
    case "Pu5": selectedQuantity = (Integer) puSpinner5.getValue(); break;
    case "Pu6": selectedQuantity = (Integer) puSpinner6.getValue(); break;

    case "P1": selectedQuantity = (Integer) pSpinner1.getValue(); break;
    case "P2": selectedQuantity = (Integer) pSpinner2.getValue(); break;
    case "P3": selectedQuantity = (Integer) pSpinner3.getValue(); break;
    case "P4": selectedQuantity = (Integer) pSpinner4.getValue(); break;
    case "P5": selectedQuantity = (Integer) pSpinner5.getValue(); break;
    case "P6": selectedQuantity = (Integer) pSpinner6.getValue(); break;

    case "Ph1": selectedQuantity = (Integer) phSpinner1.getValue(); break;
    case "Ph2": selectedQuantity = (Integer) phSpinner2.getValue(); break;
    case "Ph3": selectedQuantity = (Integer) phSpinner3.getValue(); break;
    case "Ph4": selectedQuantity = (Integer) phSpinner4.getValue(); break;
    case "Ph5": selectedQuantity = (Integer) phSpinner5.getValue(); break;
    case "Ph6": selectedQuantity = (Integer) phSpinner6.getValue(); break;

    default: selectedQuantity = 0;
    }

// Check if quantity is valid
    if (selectedQuantity == 0) {
    JOptionPane.showMessageDialog(this, "Quantity is zero. Please set a valid quantity before adding.");
    return;
}

// Passed all checks
    JOptionPane.showMessageDialog(this, "Order Selected.");

// Calculate total
    double price = foodPrices.get(selectedFood);
    double totalAmount = price * selectedQuantity;

// Get food display name
    String foodDisplayName = switch (selectedFood) {
    case "Pu1" -> "Pu1 Adobong Asting";
    case "Pu2" -> "Pu2 Asim-Tamis Sinigang";
    case "Pu3" -> "Pu3 Kanto Kare-Kare";
    case "Pu4" -> "Pu4 Menudong Masa";
    case "Pu5" -> "Pu5 Express Lang Bicol";
    case "Pu6" -> "Pu6 Tila-Perfect";

    case "P1" -> "P1 Bulaklak Blask";
    case "P2" -> "P2 Tropa Tokwa Baboy";
    case "P3" -> "P3 Sizzlin' Sisig Sarap";
    case "P4" -> "P4 Shanghai Sarap Sticks";
    case "P5" -> "P5 Kanto Kwek Attack";
    case "P6" -> "P6 Isaw Wow";

    case "Ph1" -> "Ph1 Halo Haloin Mo";
    case "Ph2" -> "Ph2 Turrific Turon";
    case "Ph3" -> "Ph3 Flantastic Delight";
    case "Ph4" -> "Ph4 Maissarap";
    case "Ph5" -> "Ph5 Biko Bida";
    case "Ph6" -> "Ph6 Minatamis";

    default -> selectedFood;
    };

// Add order to table
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{foodDisplayName, selectedQuantity, totalAmount});
    updateTotalAmount();

// Reset spinner to 0
    switch (selectedFood) {
    case "Pu1": puSpinner1.setValue(0); break;
    case "Pu2": puSpinner2.setValue(0); break;
    case "Pu3": puSpinner3.setValue(0); break;
    case "Pu4": puSpinner4.setValue(0); break;
    case "Pu5": puSpinner5.setValue(0); break;
    case "Pu6": puSpinner6.setValue(0); break;

    case "P1": pSpinner1.setValue(0); break;
    case "P2": pSpinner2.setValue(0); break;
    case "P3": pSpinner3.setValue(0); break;
    case "P4": pSpinner4.setValue(0); break;
    case "P5": pSpinner5.setValue(0); break;
    case "P6": pSpinner6.setValue(0); break;

    case "Ph1": phSpinner1.setValue(0); break;
    case "Ph2": phSpinner2.setValue(0); break;
    case "Ph3": phSpinner3.setValue(0); break;
    case "Ph4": phSpinner4.setValue(0); break;
    case "Ph5": phSpinner5.setValue(0); break;
    case "Ph6": phSpinner6.setValue(0); break;
}

// Clear selected food for safety
    selectedFood = "";
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a row to update.");
    return;
    }

    String selectedFoodDisplay = (String) jTable1.getValueAt(selectedRow, 0);
    int updatedQuantity = 0;
    double pricePerItem = 0.0;
    String foodCode = "";

switch (selectedFoodDisplay) {
    case "Pu1 Adobong Asting":
        updatedQuantity = (Integer) puSpinner1.getValue();
        pricePerItem = foodPrices.get("Pu1");
        foodCode = "Pu1";
        break;
    case "Pu2 Asim-Tamis Sinigang":
        updatedQuantity = (Integer) puSpinner2.getValue();
        pricePerItem = foodPrices.get("Pu2");
        foodCode = "Pu2";
        break;
    case "Pu3 Kanto Kare-Kare":
        updatedQuantity = (Integer) puSpinner3.getValue();
        pricePerItem = foodPrices.get("Pu3");
        foodCode = "Pu3";
        break;
    case "Pu4 Menudong Masa":
        updatedQuantity = (Integer) puSpinner4.getValue();
        pricePerItem = foodPrices.get("Pu4");
        foodCode = "Pu4";
        break;
    case "Pu5 Express Lang Bicol":
        updatedQuantity = (Integer) puSpinner5.getValue();
        pricePerItem = foodPrices.get("Pu5");
        foodCode = "Pu5";
        break;
    case "Pu6 Tila-Perfect":
        updatedQuantity = (Integer) puSpinner6.getValue();
        pricePerItem = foodPrices.get("Pu6");
        foodCode = "Pu6";
        break;
    case "P1 Bulaklak Blask":
        updatedQuantity = (Integer) pSpinner1.getValue();
        pricePerItem = foodPrices.get("P1");
        foodCode = "P1";
        break;
    case "P2 Tropa Tokwa Baboy":
        updatedQuantity = (Integer) pSpinner2.getValue();
        pricePerItem = foodPrices.get("P2");
        foodCode = "P2";
        break;
    case "P3 Sizzlin' Sisig Sarap":
        updatedQuantity = (Integer) pSpinner3.getValue();
        pricePerItem = foodPrices.get("P3");
        foodCode = "P3";
        break;
    case "P4 Shanghai Sarap Sticks":
        updatedQuantity = (Integer) pSpinner4.getValue();
        pricePerItem = foodPrices.get("P4");
        foodCode = "P4";
        break;
    case "P5 Kanto Kwek Attack":
        updatedQuantity = (Integer) pSpinner5.getValue();
        pricePerItem = foodPrices.get("P5");
        foodCode = "P5";
        break;
    case "P6 Isaw Wow":
        updatedQuantity = (Integer) pSpinner6.getValue();
        pricePerItem = foodPrices.get("P6");
        foodCode = "P6";
        break;
    case "Ph1 Halo Haloin Mo":
        updatedQuantity = (Integer) phSpinner1.getValue();
        pricePerItem = foodPrices.get("Ph1");
        foodCode = "Ph1";
        break;
    case "Ph2 Turrific Turon":
        updatedQuantity = (Integer) phSpinner2.getValue();
        pricePerItem = foodPrices.get("Ph2");
        foodCode = "Ph2";
        break;
    case "Ph3 Flantastic Delight":
        updatedQuantity = (Integer) phSpinner3.getValue();
        pricePerItem = foodPrices.get("Ph3");
        foodCode = "Ph3";
        break;
    case "Ph4 Maissarap":
        updatedQuantity = (Integer) phSpinner4.getValue();
        pricePerItem = foodPrices.get("Ph4");
        foodCode = "Ph4";
        break;
    case "Ph5 Biko Bida":
        updatedQuantity = (Integer) phSpinner5.getValue();
        pricePerItem = foodPrices.get("Ph5");
        foodCode = "Ph5";
        break;
    case "Ph6 Minatamis":
        updatedQuantity = (Integer) phSpinner6.getValue();
        pricePerItem = foodPrices.get("Ph6");
        foodCode = "Ph6";
        break;
         default:
        JOptionPane.showMessageDialog(this, "Invalid food item.");
        return;
    }

    double updatedTotal = updatedQuantity * pricePerItem;

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setValueAt(updatedQuantity, selectedRow, 1);
    model.setValueAt(updatedTotal, selectedRow, 2);

    updateTotalAmount();
    JOptionPane.showMessageDialog(this, "Order updated successfully.");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     int selectedRow = jTable1.getSelectedRow();
if (selectedRow != -1) {
    String selectedFood = (String) jTable1.getValueAt(selectedRow, 0);
    int quantity = (int) jTable1.getValueAt(selectedRow, 1);

    Consumer<JSpinner> focusSpinner = spinner -> {
        spinner.setValue(quantity);
        JComponent editor = spinner.getEditor();
        if (editor instanceof JSpinner.DefaultEditor) {
            JTextField textField = ((JSpinner.DefaultEditor) editor).getTextField();
            textField.requestFocusInWindow();
            textField.selectAll();
        }
    };

    switch (selectedFood) {
        case "Pu1 Adobong Asting":
            focusSpinner.accept(puSpinner1);
            break;
        case "Pu2 Asim-Tamis Sinigang":
            focusSpinner.accept(puSpinner2);
            break;
        case "Pu3 Kanto Kare-Kare":
            focusSpinner.accept(puSpinner3);
            break;
        case "Pu4 Menudong Masa":
            focusSpinner.accept(puSpinner4);
            break;
        case "Pu5 Express Lang Bicol":
            focusSpinner.accept(puSpinner5);
            break;
        case "Pu6 Tila-Perfect":
            focusSpinner.accept(puSpinner6);
            break;

        case "P1 Bulaklak Blask":
            focusSpinner.accept(pSpinner1);
            break;
        case "P2 Tropa Tokwa Baboy":
            focusSpinner.accept(pSpinner2);
            break;
        case "P3 Sizzlin' Sisig Sarap":
            focusSpinner.accept(pSpinner3);
            break;
        case "P4 Shanghai Sarap Sticks":
            focusSpinner.accept(pSpinner4);
            break;
        case "P5 Kanto Kwek Attack":
            focusSpinner.accept(pSpinner5);
            break;
        case "P6 Isaw Wow":
            focusSpinner.accept(pSpinner6);
            break;

        case "Ph1 Halo Haloin Mo":
            focusSpinner.accept(phSpinner1);
            break;
        case "Ph2 Turrific Turon":
            focusSpinner.accept(phSpinner2);
            break;
        case "Ph3 Flantastic Delight":
            focusSpinner.accept(phSpinner3);
            break;
        case "Ph4 Maissarap":
            focusSpinner.accept(phSpinner4);
            break;
        case "Ph5 Biko Bida":
            focusSpinner.accept(phSpinner5);
            break;
        case "Ph6 Minatamis":
            focusSpinner.accept(phSpinner6);
            break;

        default:
            JOptionPane.showMessageDialog(this, "Food item not recognized.");
            break;
    }
}
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KantoKusina_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KantoKusina_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KantoKusina_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KantoKusina_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KantoKusina_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panghimagas;
    private javax.swing.JPanel Pulutan;
    private javax.swing.JPanel Ulam;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner pSpinner1;
    private javax.swing.JSpinner pSpinner2;
    private javax.swing.JSpinner pSpinner3;
    private javax.swing.JSpinner pSpinner4;
    private javax.swing.JSpinner pSpinner5;
    private javax.swing.JSpinner pSpinner6;
    private javax.swing.JSpinner phSpinner1;
    private javax.swing.JSpinner phSpinner2;
    private javax.swing.JSpinner phSpinner3;
    private javax.swing.JSpinner phSpinner4;
    private javax.swing.JSpinner phSpinner5;
    private javax.swing.JSpinner phSpinner6;
    private javax.swing.JSpinner puSpinner1;
    private javax.swing.JSpinner puSpinner2;
    private javax.swing.JSpinner puSpinner3;
    private javax.swing.JSpinner puSpinner4;
    private javax.swing.JSpinner puSpinner5;
    private javax.swing.JSpinner puSpinner6;
    // End of variables declaration//GEN-END:variables
}
