/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRAMES;

import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author REGIE
 */
public class YankeeBite extends javax.swing.JFrame {
     DefaultTableModel model =  new DefaultTableModel();
     HashMap<String, Double> foodPrices = new HashMap<>();

    private String selectedFood = "";
    private double selectedPrice = 0.0;
    private int selectedQuantity = 1;
  
    public YankeeBite() {
        initComponents();
        
        foodPrices.put("Hm1", 80.00);
        foodPrices.put("Hm2", 110.00);
        foodPrices.put("Hm3", 60.00); 
        foodPrices.put("Hm4", 110.00); 
        foodPrices.put("Hm5", 120.00); 
        foodPrices.put("Hm6", 150.00); 
        
        foodPrices.put("Bf1", 100.00); 
        foodPrices.put("Bf2", 130.00); 
        foodPrices.put("Bf3", 120.00); 
        foodPrices.put("Bf4", 80.00); 
        foodPrices.put("Bf5", 80.00); 
        foodPrices.put("Bf6", 80.00); 
        
        foodPrices.put("B1", 80.00); 
        foodPrices.put("B2", 80.00); 
        foodPrices.put("B3", 50.00); 
        foodPrices.put("B4", 50.00); 
        foodPrices.put("B5", 50.00); 
        foodPrices.put("B6", 50.00); 
        
        foodPrices.put("D1", 50.00); 
        foodPrices.put("D2", 50.00); 
        foodPrices.put("D3", 50.00); 
        foodPrices.put("D4", 50.00); 
    }
    
     private void updateTotalAmount() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    double total = 0.0;
    for (int i = 0; i < model.getRowCount(); i++) {
        Object amountValue = model.getValueAt(i, 2);
        if (amountValue instanceof Number) {
            total += ((Number) amountValue).doubleValue();
        } else if (amountValue instanceof String) {
            try {
                total += Double.parseDouble((String) amountValue);
            } catch (NumberFormatException e) {
                // ignore invalid numbers
            }
        }
    }
    jLabel2.setText("₱" + String.format("%.2f", total));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Category = new javax.swing.JPanel();
        Burger = new javax.swing.JPanel();
        Bf1 = new javax.swing.JButton();
        Bf2 = new javax.swing.JButton();
        Bf3 = new javax.swing.JButton();
        Bf4 = new javax.swing.JButton();
        Bf5 = new javax.swing.JButton();
        Bf6 = new javax.swing.JButton();
        bfSpinner1 = new javax.swing.JSpinner();
        bfSpinner2 = new javax.swing.JSpinner();
        bfSpinner3 = new javax.swing.JSpinner();
        bfSpinner4 = new javax.swing.JSpinner();
        bfSpinner5 = new javax.swing.JSpinner();
        bfSpinner6 = new javax.swing.JSpinner();
        Breakfast = new javax.swing.JPanel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        bSpinner1 = new javax.swing.JSpinner();
        bSpinner2 = new javax.swing.JSpinner();
        bSpinner3 = new javax.swing.JSpinner();
        bSpinner4 = new javax.swing.JSpinner();
        bSpinner5 = new javax.swing.JSpinner();
        bSpinner6 = new javax.swing.JSpinner();
        Drinks = new javax.swing.JPanel();
        D1 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        dSpinner1 = new javax.swing.JSpinner();
        dSpinner2 = new javax.swing.JSpinner();
        dSpinner3 = new javax.swing.JSpinner();
        dSpinner4 = new javax.swing.JSpinner();
        HeavyMeal = new javax.swing.JPanel();
        Hm1 = new javax.swing.JButton();
        Hm2 = new javax.swing.JButton();
        Hm3 = new javax.swing.JButton();
        Hm4 = new javax.swing.JButton();
        Hm5 = new javax.swing.JButton();
        Hm6 = new javax.swing.JButton();
        hmSpinner1 = new javax.swing.JSpinner();
        hmSpinner2 = new javax.swing.JSpinner();
        hmSpinner3 = new javax.swing.JSpinner();
        hmSpinner4 = new javax.swing.JSpinner();
        hmSpinner5 = new javax.swing.JSpinner();
        hmSpinner6 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 800));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(699, 125));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 700));

        jButton2.setText("ADD ORDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE ORDER");

        jButton4.setText("UPDATE ORDER");

        jButton8.setText("PAY");

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/5.png"))); // NOI18N
        jButton9.setText("jButton9");
        jButton9.setBorderPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/1.png"))); // NOI18N
        jButton10.setText("jButton9");
        jButton10.setBorderPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/2.png"))); // NOI18N
        jButton11.setText("jButton9");
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/3.png"))); // NOI18N
        jButton12.setText("jButton9");
        jButton12.setBorderPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(240, 240, 240)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(335, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(549, 240));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORDER", "QUANTITY", "AMOUNT", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("TOTAL AMOUNT:");

        jLabel2.setText("TOTAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        Category.setBackground(new java.awt.Color(255, 255, 255));
        Category.setLayout(new javax.swing.OverlayLayout(Category));

        Burger.setBackground(new java.awt.Color(255, 255, 255));

        Bf1.setBackground(new java.awt.Color(255, 255, 255));
        Bf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/7.png"))); // NOI18N
        Bf1.setText("BF1");
        Bf1.setBorderPainted(false);
        Bf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bf1ActionPerformed(evt);
            }
        });

        Bf2.setBackground(new java.awt.Color(255, 255, 255));
        Bf2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/8.png"))); // NOI18N
        Bf2.setText("BF2");
        Bf2.setBorderPainted(false);
        Bf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bf2ActionPerformed(evt);
            }
        });

        Bf3.setBackground(new java.awt.Color(255, 255, 255));
        Bf3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/9.png"))); // NOI18N
        Bf3.setText("BF3");
        Bf3.setBorderPainted(false);
        Bf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bf3ActionPerformed(evt);
            }
        });

        Bf4.setBackground(new java.awt.Color(255, 255, 255));
        Bf4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/10.png"))); // NOI18N
        Bf4.setText("BF4");
        Bf4.setBorderPainted(false);
        Bf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bf4ActionPerformed(evt);
            }
        });

        Bf5.setBackground(new java.awt.Color(255, 255, 255));
        Bf5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/11.png"))); // NOI18N
        Bf5.setText("BF5");
        Bf5.setBorderPainted(false);
        Bf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bf5ActionPerformed(evt);
            }
        });

        Bf6.setBackground(new java.awt.Color(255, 255, 255));
        Bf6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/12.png"))); // NOI18N
        Bf6.setText("BF6");
        Bf6.setBorderPainted(false);
        Bf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bf6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BurgerLayout = new javax.swing.GroupLayout(Burger);
        Burger.setLayout(BurgerLayout);
        BurgerLayout.setHorizontalGroup(
            BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BurgerLayout.createSequentialGroup()
                .addGroup(BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BurgerLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(bfSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BurgerLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BurgerLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bfSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Bf1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Bf4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29)
                .addGroup(BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bf2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bf5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BurgerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bfSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bfSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bf3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bf6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BurgerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bfSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bfSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        BurgerLayout.setVerticalGroup(
            BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BurgerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bf1)
                    .addComponent(Bf2)
                    .addComponent(Bf3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bfSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bfSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bfSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bf4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bf5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bf6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bfSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bfSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bfSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(948, Short.MAX_VALUE))
        );

        Category.add(Burger);

        Breakfast.setBackground(new java.awt.Color(255, 255, 255));

        B1.setBackground(new java.awt.Color(255, 255, 255));
        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/13.png"))); // NOI18N
        B1.setText("B1");
        B1.setBorderPainted(false);

        B2.setBackground(new java.awt.Color(255, 255, 255));
        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/14.png"))); // NOI18N
        B2.setText("B2");
        B2.setBorderPainted(false);

        B3.setBackground(new java.awt.Color(255, 255, 255));
        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/15.png"))); // NOI18N
        B3.setText("B3");
        B3.setBorderPainted(false);

        B4.setBackground(new java.awt.Color(255, 255, 255));
        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/16.png"))); // NOI18N
        B4.setText("B4");
        B4.setBorderPainted(false);

        B5.setBackground(new java.awt.Color(255, 255, 255));
        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/17.png"))); // NOI18N
        B5.setText("B5");
        B5.setBorderPainted(false);

        B6.setBackground(new java.awt.Color(255, 255, 255));
        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/18.png"))); // NOI18N
        B6.setText("B6");
        B6.setBorderPainted(false);

        javax.swing.GroupLayout BreakfastLayout = new javax.swing.GroupLayout(Breakfast);
        Breakfast.setLayout(BreakfastLayout);
        BreakfastLayout.setHorizontalGroup(
            BreakfastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BreakfastLayout.createSequentialGroup()
                .addGroup(BreakfastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BreakfastLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(bSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 185, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BreakfastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BreakfastLayout.createSequentialGroup()
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BreakfastLayout.createSequentialGroup()
                            .addGroup(BreakfastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(BreakfastLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(bSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(BreakfastLayout.createSequentialGroup()
                                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addGap(32, 32, 32)))
                            .addGroup(BreakfastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(BreakfastLayout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(bSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(BreakfastLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(bSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(26, 26, 26)
                .addGroup(BreakfastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BreakfastLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(BreakfastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        BreakfastLayout.setVerticalGroup(
            BreakfastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BreakfastLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(BreakfastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1)
                    .addComponent(B2)
                    .addComponent(B3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BreakfastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(BreakfastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B4)
                    .addComponent(B5)
                    .addComponent(B6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BreakfastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(950, Short.MAX_VALUE))
        );

        Category.add(Breakfast);

        Drinks.setBackground(new java.awt.Color(255, 255, 255));

        D1.setBackground(new java.awt.Color(255, 255, 255));
        D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/25.png"))); // NOI18N
        D1.setText("D1");
        D1.setBorderPainted(false);

        D2.setBackground(new java.awt.Color(255, 255, 255));
        D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/26.png"))); // NOI18N
        D2.setText("D2");
        D2.setBorderPainted(false);

        D3.setBackground(new java.awt.Color(255, 255, 255));
        D3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/27.png"))); // NOI18N
        D3.setText("D3");
        D3.setBorderPainted(false);
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });

        D4.setBackground(new java.awt.Color(255, 255, 255));
        D4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/28.png"))); // NOI18N
        D4.setText("D4");
        D4.setBorderPainted(false);

        javax.swing.GroupLayout DrinksLayout = new javax.swing.GroupLayout(Drinks);
        Drinks.setLayout(DrinksLayout);
        DrinksLayout.setHorizontalGroup(
            DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrinksLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DrinksLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(dSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DrinksLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(dSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        DrinksLayout.setVerticalGroup(
            DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrinksLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(954, Short.MAX_VALUE))
        );

        Category.add(Drinks);

        HeavyMeal.setBackground(new java.awt.Color(255, 255, 255));
        HeavyMeal.setPreferredSize(new java.awt.Dimension(630, 1377));

        Hm1.setBackground(new java.awt.Color(255, 255, 255));
        Hm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/1_1.png"))); // NOI18N
        Hm1.setText("HM1");
        Hm1.setBorderPainted(false);
        Hm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hm1ActionPerformed(evt);
            }
        });

        Hm2.setBackground(new java.awt.Color(255, 255, 255));
        Hm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/2_1.png"))); // NOI18N
        Hm2.setText("HM2");
        Hm2.setBorderPainted(false);
        Hm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hm2ActionPerformed(evt);
            }
        });

        Hm3.setBackground(new java.awt.Color(255, 255, 255));
        Hm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/3_1.png"))); // NOI18N
        Hm3.setText("HM3");
        Hm3.setBorderPainted(false);
        Hm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hm3ActionPerformed(evt);
            }
        });

        Hm4.setBackground(new java.awt.Color(255, 255, 255));
        Hm4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/4_1.png"))); // NOI18N
        Hm4.setText("HM4");
        Hm4.setBorderPainted(false);
        Hm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hm4ActionPerformed(evt);
            }
        });

        Hm5.setBackground(new java.awt.Color(255, 255, 255));
        Hm5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/5_1.png"))); // NOI18N
        Hm5.setText("HM5");
        Hm5.setBorderPainted(false);
        Hm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hm5ActionPerformed(evt);
            }
        });

        Hm6.setBackground(new java.awt.Color(255, 255, 255));
        Hm6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEYANKEE/6.png"))); // NOI18N
        Hm6.setText("HM6");
        Hm6.setBorderPainted(false);
        Hm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hm6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeavyMealLayout = new javax.swing.GroupLayout(HeavyMeal);
        HeavyMeal.setLayout(HeavyMealLayout);
        HeavyMealLayout.setHorizontalGroup(
            HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeavyMealLayout.createSequentialGroup()
                .addGroup(HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeavyMealLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Hm4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hm1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(HeavyMealLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hmSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hmSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addGroup(HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Hm2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Hm5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HeavyMealLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hmSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hmSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Hm3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hm6, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addGroup(HeavyMealLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hmSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hmSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        HeavyMealLayout.setVerticalGroup(
            HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeavyMealLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hm2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Hm3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Hm1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hmSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hmSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hmSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hm4)
                    .addComponent(Hm5)
                    .addComponent(Hm6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HeavyMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hmSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hmSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hmSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(950, 950, 950))
        );

        Category.add(HeavyMeal);

        jScrollPane2.setViewportView(Category);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       HeavyMeal.setVisible(true);
       Breakfast.setVisible(false);
       Burger.setVisible(false);
       Drinks.setVisible(false);
       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
         HeavyMeal.setVisible(false);
       Breakfast.setVisible(false);
       Burger.setVisible(true);
       Drinks.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         HeavyMeal.setVisible(false);
       Breakfast.setVisible(true);
       Burger.setVisible(false);
       Drinks.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         HeavyMeal.setVisible(false);
       Breakfast.setVisible(false);
       Burger.setVisible(false);
       Drinks.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D3ActionPerformed

    private void Bf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bf1ActionPerformed
       selectedFood = "Bf1";
    selectedPrice = foodPrices.get("Bf1");
    }//GEN-LAST:event_Bf1ActionPerformed

    private void Hm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hm1ActionPerformed
        selectedFood = "Hm1";
    selectedPrice = foodPrices.get("Hm1");
    }//GEN-LAST:event_Hm1ActionPerformed

    private void Hm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hm2ActionPerformed
        selectedFood = "Hm2";
    selectedPrice = foodPrices.get("Hm2");
    }//GEN-LAST:event_Hm2ActionPerformed

    private void Hm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hm3ActionPerformed
        selectedFood = "Hm3";
    selectedPrice = foodPrices.get("Hm3");
    }//GEN-LAST:event_Hm3ActionPerformed

    private void Hm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hm4ActionPerformed
       selectedFood = "Hm4";
    selectedPrice = foodPrices.get("Hm4");
    }//GEN-LAST:event_Hm4ActionPerformed

    private void Hm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hm5ActionPerformed
       selectedFood = "Hm5";
    selectedPrice = foodPrices.get("Hm5");
    }//GEN-LAST:event_Hm5ActionPerformed

    private void Hm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hm6ActionPerformed
        selectedFood = "Hm6";
    selectedPrice = foodPrices.get("Hm6");
    }//GEN-LAST:event_Hm6ActionPerformed

    private void Bf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bf2ActionPerformed
        selectedFood = "Bf2";
    selectedPrice = foodPrices.get("Bf2");
    }//GEN-LAST:event_Bf2ActionPerformed

    private void Bf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bf3ActionPerformed
      selectedFood = "Bf3";
    selectedPrice = foodPrices.get("Bf3");
    }//GEN-LAST:event_Bf3ActionPerformed

    private void Bf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bf4ActionPerformed
       selectedFood = "Bf4";
    selectedPrice = foodPrices.get("Bf4");
    }//GEN-LAST:event_Bf4ActionPerformed

    private void Bf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bf5ActionPerformed
       selectedFood = "Bf5";
    selectedPrice = foodPrices.get("Bf5");
    }//GEN-LAST:event_Bf5ActionPerformed

    private void Bf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bf6ActionPerformed
       selectedFood = "Bf6";
    selectedPrice = foodPrices.get("Bf6");
    }//GEN-LAST:event_Bf6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if (selectedFood.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a food item first.");
        return;
    } else {
            JOptionPane.showMessageDialog(this, "Order Selected.");
        }

   
    
    switch (selectedFood) {
        case "Hm1":
            selectedQuantity = (Integer) hmSpinner1.getValue();
            break;
        case "Hm2":
            selectedQuantity = (Integer) hmSpinner2.getValue();
            break;
        case "Hm3":
            selectedQuantity = (Integer) hmSpinner3.getValue();
            break;
        case "Hm4":
            selectedQuantity = (Integer) hmSpinner4.getValue();
            break;  
        case "Hm5":
            selectedQuantity = (Integer) hmSpinner5.getValue();
            break;
        case "Hm6":
            selectedQuantity = (Integer) hmSpinner6.getValue();
            break;
        case "Bf1":
            selectedQuantity = (Integer) bfSpinner1.getValue();
            break;
        case "Bf2":
            selectedQuantity = (Integer) bfSpinner2.getValue();
            break;
        case "Bf3":
            selectedQuantity = (Integer) bfSpinner3.getValue();
            break;
        case "Bf4":
            selectedQuantity = (Integer) bfSpinner4.getValue();
            break;
        case "Bf5":
            selectedQuantity = (Integer) bfSpinner5.getValue();
            break;
        case "Bf6":
            selectedQuantity = (Integer) bfSpinner6.getValue();
            break;
    }

    double price = foodPrices.get(selectedFood);
    double totalAmount = price * selectedQuantity;

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{selectedFood, selectedQuantity, totalAmount});
    updateTotalAmount();

    switch (selectedFood) {
        case "Hm1":
            hmSpinner1.setValue(0);
            break;
        case "Hm2":
            hmSpinner2.setValue(0);
            break;
        case "Hm3":
            hmSpinner3.setValue(0);
            break;
        case "Hm4":
            hmSpinner4.setValue(0);
            break;  
        case "Hm5":
            hmSpinner5.setValue(0);
            break;
        case "Hm6":
            hmSpinner6.setValue(0);
            break;
        case "Bf1":
            bfSpinner1.setValue(0);
            break;
        case "Bf2":
            bfSpinner2.setValue(0);
            break;
        case "Bf3":
            bfSpinner3.setValue(0);
            break;
        case "Bf4":
            bfSpinner4.setValue(0);
            break;
        case "Bf5":
            bfSpinner5.setValue(0);
            break;
        case "Bf6":
            bfSpinner6.setValue(0);
            break;
    }
    
    selectedFood = "";
           
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YankeeBite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YankeeBite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YankeeBite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YankeeBite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YankeeBite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton Bf1;
    private javax.swing.JButton Bf2;
    private javax.swing.JButton Bf3;
    private javax.swing.JButton Bf4;
    private javax.swing.JButton Bf5;
    private javax.swing.JButton Bf6;
    private javax.swing.JPanel Breakfast;
    private javax.swing.JPanel Burger;
    private javax.swing.JPanel Category;
    private javax.swing.JButton D1;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JPanel Drinks;
    private javax.swing.JPanel HeavyMeal;
    private javax.swing.JButton Hm1;
    private javax.swing.JButton Hm2;
    private javax.swing.JButton Hm3;
    private javax.swing.JButton Hm4;
    private javax.swing.JButton Hm5;
    private javax.swing.JButton Hm6;
    private javax.swing.JSpinner bSpinner1;
    private javax.swing.JSpinner bSpinner2;
    private javax.swing.JSpinner bSpinner3;
    private javax.swing.JSpinner bSpinner4;
    private javax.swing.JSpinner bSpinner5;
    private javax.swing.JSpinner bSpinner6;
    private javax.swing.JSpinner bfSpinner1;
    private javax.swing.JSpinner bfSpinner2;
    private javax.swing.JSpinner bfSpinner3;
    private javax.swing.JSpinner bfSpinner4;
    private javax.swing.JSpinner bfSpinner5;
    private javax.swing.JSpinner bfSpinner6;
    private javax.swing.JSpinner dSpinner1;
    private javax.swing.JSpinner dSpinner2;
    private javax.swing.JSpinner dSpinner3;
    private javax.swing.JSpinner dSpinner4;
    private javax.swing.JSpinner hmSpinner1;
    private javax.swing.JSpinner hmSpinner2;
    private javax.swing.JSpinner hmSpinner3;
    private javax.swing.JSpinner hmSpinner4;
    private javax.swing.JSpinner hmSpinner5;
    private javax.swing.JSpinner hmSpinner6;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
